config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users

  resources :shoots

  resources :posts do
    resources :comments
  end

  resources :galleries do
    resources :videos
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :name, :presence => true
  validates :content, :presence => true
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :videos, dependent: :destroy

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :name, :presence => true
  validates :title, :presence => true
  validates :content, :presence => true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/shoot.rb
class Shoot < ApplicationRecord

  has_attached_file :pdf, :styles => { :thumb => ["100x100#", :png] }
  validates_attachment :pdf, content_type: { content_type: "application/pdf" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
  validates :password, uniqueness: true

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :gallery


  has_attached_file :clip, :styles => {
  :medium => { :geometry => "640x480", :format => 'flv' },
  :thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10 }
},  :processors => [:transcoder]

validates_attachment :clip, content_type: { content_type: "video/mp4" }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_admin
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :admin])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :admin])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :current_password, :admin])
  end
end

app/controllers/coments_controller.rb
class CommentsController < ApplicationRecord

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to_post_path(@comment.post)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(parms[:post_id])
    @comment = Comment.find(:id)
    @comment.destroy
    redirect_to_post_path(@comment.post)
  end

  private
  def post_params
    params.require(:comment).permit(:name, :content)

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :content)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]

  before_action :only => [:new, :create, :edit, :update, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      redirect_to galleries_path
    else
      render :new
    end
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update(gallery_params)
      redirect_to galleries_path
    else
      render :edit
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    redirect_to galleries_path
  end

private
  def gallery_params
    params.require(:gallery).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]

  before_action :only => [:new, :create, :edit, :update, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

private
  def post_params
    params.require(:post).permit(:name, :title, :content, :avatar)
  end
end

app/controllers/shoots_controller.rb
class ShootsController < ApplicationController
  before_action :set_shoot, only: [:show, :edit, :update, :destroy]

  # GET /shoots
  # GET /shoots.json
  def index
    @shoots = Shoot.all
    @date = params[:month] ? Date.parse(params[:month].gsub('-', '/')) : Date.today
  end

  # GET /shoots/1
  # GET /shoots/1.json
  def show
  end

  # GET /shoots/new
  def new
    @shoot = Shoot.new
  end

  # GET /shoots/1/edit
  def edit
    @shoot = Shoot.find(params[:id])
  end

  # POST /shoots
  # POST /shoots.json
  def create
    @shoot = Shoot.new(shoot_params)

    respond_to do |format|
      if @shoot.save
        format.html { redirect_to @shoot, notice: 'Shoot was successfully created.' }
        format.json { render :show, status: :created, location: @shoot }
      else
        format.html { render :new }
        format.json { render json: @shoot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoots/1
  # PATCH/PUT /shoots/1.json
  def update
    respond_to do |format|
      if @shoot.update(shoot_params)
        format.html { redirect_to @shoot, notice: 'Shoot was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoot }
      else
        format.html { render :edit }
        format.json { render json: @shoot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoots/1
  # DELETE /shoots/1.json
  def destroy
    @shoot.destroy
    respond_to do |format|
      format.html { redirect_to shoots_url, notice: 'Shoot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoot
      @shoot = Shoot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoot_params
      params.require(:shoot).permit(:name, :start_time, :pdf)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def new
    @gallery = Gallery.find(params[:gallery_id])
    @video = @gallery.videos.new
  end

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @video = @gallery.videos.new(video_params)
    if @video.save
      redirect_to gallery_path(@video.gallery)
    else
      render :new
    end
  end

  def destroy
    @gallery = Gallery.find(params[:gallery_id])
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to gallery_path(@gallery)
  end

  private
  def video_params
    params.require(:video).permit(:description, :clip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shoots_helper.rb
module ShootsHelper
end

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :content %>
  <br>
  <%= f.text_area :content %>
  <br>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/new.html.erb
<h1>New comment for <%= @post.name %></h1>

<%= render 'form' %>
<hr>

app/views/galleries/_form.html.erb
<%= render "layouts/errors", :object => @gallery %>

<%= form_for @gallery do |f| %>
  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <br>
  <%= f.text_field :description %>
  <br>
  <div class="button">
    <%= f.submit  %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Edit gallery:</h1>
<%= render "form" %>
<hr>

app/views/galleries/index.html.erb
<% @galleries.each do |gallery| %>
  <h3><%= link_to gallery.title, gallery_path(gallery)%></h3>

<% end %>

app/views/galleries/new.html.erb
<h1>New gallery:</h1>
<%= render "form" %>
<hr>

app/views/galleries/show.html.erb
<div class="container">
  <h2><%= @gallery.title %></h2>
  <h3><%= @gallery.description %></h3>
   <br>
  <br>
  <% if current_user.try(:admin?) %>
  <p><%= link_to "Edit Gallery", edit_gallery_path(@gallery) %></p>
  <p><%= link_to "Delete Gallery", gallery_path(@gallery), :data => {:confirm => "You sure?", :method => "delete"} %></p>
  <% end %>

  <h3>Clips:</h3>
  <p><%= link_to "Add Clip", new_gallery_video_path(@gallery) %></p>

    <% @gallery.videos.each do |video| %>
          <%= image_tag "#{video.clip}" %>



      <% if current_user.try(:admin?) %>
      <p><%= link_to "Delete Clip", gallery_video_path(@gallery, video), :data => {:confirm => "You sure?", :method => "delete"} %></p>
      <% end %>
      <br>
<% end %>
</div>

app/views/home/index.html.erb
<div style="background-repeat:no-repeat;">

  <%= image_tag "home.jpg" %>
</div>
<!-- {
    background-image: url(http://leydenlewis.com/images/LANDING_PAGE.jpg);
    background-repeat: no-repeat;
    background-position: 0 0;
    background-size: cover;
} -->

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FilmProject</title>
  <link rel="stylesheet" href="css/styles.css">
  <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
  <script src="js/tuxedo.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <nav class="nav-dark fixed">
    <h2>FilmProject</h2>
  </nav>
  <div class="side-bar bg-dark-grey">

    <ul class="underline-light">
      <% if current_user %>
      <li><%= link_to "Updates",  posts_path %></li>
      <li><%= link_to "Shoots",  shoots_path %></li>
    </ul>
    <ul>
      <li> <%= link_to "Sign out", destroy_user_session_path, method: 'delete' %></li>
    </ul>

    <% else %>
    <li><%= link_to 'Sign In', new_user_session_path %></li>
    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <% end %>
  </ul>
</div>
<div class="side-bar-content">
  <%= yield %>
</div>
</body>
</div>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <br>
  <%= f.text_area :content %>
  <br>
  <%= f.label :image  %>
  <br>
  <%= f.file_field :avatar %>
  <br>
  <div class="button">
    <%= f.submit  %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post:</h1>
<%= render "form" %>
<hr>

app/views/posts/index.html.erb
<h1>Updates</h1>
<p><%= link_to "Add Update", new_post_path %></p>
<% @posts.each do |post| %>
  <h5><%= link_to post.title, post_path(post)%></h5>

<% end %>

app/views/posts/new.html.erb
<h1>New post:</h1>
<%= render "form" %>
<hr>

app/views/posts/show.html.erb
<div class="container">
  <h2><%= @post.name %></h2>
  <% if @post.avatar.exists? %>
  <%= image_tag "#{@post.avatar}" %>
  <% end %>
  <h4><%= @post.title %></h4>
   <br>
  <br>
  <% if current_user.try(:admin?) %>
  <p><%= link_to "Edit Post", edit_post_path(@post) %></p>
  <p><%= link_to "Delete Post", post_path(@post), :data => {:confirm => "You sure?", :method => "delete"} %></p>
  <% end %>

  <h3>Comments:</h3>
  <p><%= link_to "Add Comment", new_post_comment_path(@post) %></p>
  <% @post.comments.each do |comment| %>
        <h4> "<%= comment.content %>" </h4>

      <% if current_user.try(:admin?) %>
      <p><%= link_to "Delete Comment", post_comment_path(@post, comment), :data => {:confirm => "You sure?", :method => "delete"} %></p>
      <% end %>
      <br>
<% end %>
</div>

app/views/shoots/_form.html.erb
<%= form_with(model: shoot, local: true) do |form| %>
  <% if shoot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shoot.errors.count, "error") %> prohibited this shoot from being saved:</h2>

      <ul>
      <% shoot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :shoot_name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :shoot_start_time %>
  </div>

  <div class="field">
    <%= form.label :pdf  %>
    <%= form.file_field :pdf %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shoots/edit.html.erb
<h1>Editing Shoot</h1>

<%= render 'form', shoot: @shoot %>

<%= link_to 'Show', @shoot %> |
<%= link_to 'Back', shoots_path %>

app/views/shoots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shoots</h1>
<p><%= link_to 'New Shoot', new_shoot_path %></p>
<div id="calendar">
  <h2 id="month">
    <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m") %>
    <%=h @date.strftime("%B %Y") %>
    <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m") %>
  </h2>
  <% calendar_for @shoot, :year => @date.year, :month => @date.month do |calendar| %>
    <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
    <% calendar.day(:day_method => :start_time) do |date, shoot| %>
      <%= date.day %>
      <ul>
        <% for shoot in shoot %>
          <li><%= link_to h(shoot.name), shoot %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>
<table>
  <thead>
    <tr>
      <th><p>Name</p></th>
      <th><p>Start time</p></th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoots.each do |shoot| %>
      <tr>
        <td><p><%= link_to shoot.name, shoot_path(shoot) %></p></td>
        <td><p><%= shoot.start_time %></p></td>
      </tr>
      <tr>
        <td><p><%= link_to 'Edit', edit_shoot_path(shoot) %></p></td>
        <td><p><%= link_to 'Delete', shoot, method: :delete, data: { confirm: 'Are you sure?' } %></p></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shoots/new.html.erb
<h1>New Shoot</h1>

<%= render 'form', shoot: @shoot %>

<p><%= link_to 'Back', shoots_path %></p>

app/views/shoots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shoot.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @shoot.start_time %>
</p>

<%= link_to 'View Script', @shoot.pdf.url %>
<br><br>
<hr>
<p><%= link_to 'Edit', edit_shoot_path(@shoot) %></p>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/videos/_form.html.erb
<%= render "layouts/errors", :object => @video %>

<%= form_for [@gallery, @video] do |f| %>
  <%= f.label :description %>
  <br>
  <%= f.text_field :description %>
  <br>
  <%= f.label :clip  %>
  <br>
  <%= f.file_field :clip %>
  <br>
  <div class="button">
    <%= f.submit  %>
  </div>
<% end %>

app/views/videos/new.html.erb
<h1>Add a clip to <%= @gallery.title %></h1>

<%= render 'form' %>
<hr>